language: objective-c
osx_image: xcode7
env:
  global:
  - LC_CTYPE=en_US.UTF-8
  - LANG=en_US.UTF-8
before_install:
  - brew update
  - brew install carthage
  - carthage bootstrap --no-build
script:
  - carthage build --no-skip-current
